/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package partnersmanagement;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Tiago
 */
public class quotaGUI extends javax.swing.JFrame {
    
    private DefaultListModel dlmDate = null;
    private DefaultListModel dlmValue = null;
    private PartnersList partners;
    private String mail;
    /**
     * Creates new form quotaGUI
     */
    public quotaGUI() {
        initComponents();
    }
    
    public quotaGUI(PartnersList l, String mail){
        this.partners = l;
        this.mail = mail;
        initComponents();
    }
    
  private DefaultListModel getDateListModel(Partner p){
        if(dlmDate == null){
            dlmDate = new DefaultListModel();
            for(Quota q: p.getQuotas()){
                dlmDate.addElement(q.getDate());
            }
        }
        return dlmDate;
    }
    
    private DefaultListModel getValueListModel(Partner p){
        if(dlmValue == null){
            dlmValue = new DefaultListModel();
            for(Quota q: p.getQuotas()){
                dlmValue.addElement(q.getValue());
            }
        }
        return dlmValue;
    }
    
    private JList getDateList(){
        if(dateList == null){
            dateList = new JList();
            
            dateList.setModel(getDateListModel(this.partners.getGroup().get(this.mail)));
            dateList.setFocusCycleRoot(true);
            dateList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }
        return dateList;
    }
    
    private JList getValueList(){
        if(valueList == null){
            valueList = new JList();
            
            valueList.setModel(getValueListModel(this.partners.getGroup().get(this.mail)));
            valueList.setFocusCycleRoot(true);
            valueList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }
        return valueList;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        dateList = getDateList();
        jScrollPane3 = new javax.swing.JScrollPane();
        valueList = getValueList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(dateList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 39, 182, 247));

        jScrollPane3.setViewportView(valueList);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 39, 182, 247));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel1.setText("Data");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel2.setText("Valor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 11, -1, -1));

        payButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 13)); // NOI18N
        payButton.setText("Pagar Quota");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });
        getContentPane().add(payButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, 40));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
        new payGUI(this.partners, this.mail).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_payButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quotaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> dateList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton payButton;
    private javax.swing.JList<String> valueList;
    // End of variables declaration//GEN-END:variables
}
