/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package partnersmanagement;

/**
 *
 * @author Tiago
 */
public class partnersViewGUI extends javax.swing.JFrame {
    
    private Partner partner;
    /**
     * Creates new form partnersViewGUI
     */
    public partnersViewGUI() {
        initComponents();
    }
    
    public partnersViewGUI(Partner p){
        initComponents();
        this.partner = p;
        this.nameField.setText(this.partner.getName());
        this.mailField.setText(this.partner.getMail());
        this.addressField.setText(this.partner.getAddress());
        this.courseField.setText(this.partner.getCourse());
        this.numberField.setText(String.valueOf(this.partner.getNumber()));
        this.phoneField.setText(this.partner.getPhoneNumber());
        this.nameField.setEditable(false);
        this.mailField.setEditable(false);
        this.addressField.setEditable(false);
        this.courseField.setEditable(false);
        this.numberField.setEditable(false);
        this.phoneField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        courseField = new javax.swing.JTextField();
        mailField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        numberField = new javax.swing.JTextField();
        updateDataButton = new javax.swing.JButton();
        quotaButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel2.setText("Curso");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel3.setText("Morada");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel4.setText("Nº Sócio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel5.setText("Mail");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel6.setText("Nº tlf.");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        nameField.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 140, -1));

        courseField.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        getContentPane().add(courseField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 140, -1));

        mailField.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        getContentPane().add(mailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, -1));

        phoneField.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        getContentPane().add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 140, -1));

        addressField.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        getContentPane().add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 140, -1));

        numberField.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        getContentPane().add(numberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 140, -1));

        updateDataButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        updateDataButton.setText("Atualizar dados");
        updateDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDataButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 140, 30));

        quotaButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        quotaButton.setText("Ver Quotas");
        quotaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quotaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(quotaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 140, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel7.setText("SÓCIO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quotaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quotaButtonActionPerformed
        // TODO add your handling code here:
        new quotaGUI(this.partner).setVisible(true);
    }//GEN-LAST:event_quotaButtonActionPerformed

    private void updateDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDataButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_updateDataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(partnersViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(partnersViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(partnersViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(partnersViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new partnersViewGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField courseField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mailField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField numberField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton quotaButton;
    private javax.swing.JButton updateDataButton;
    // End of variables declaration//GEN-END:variables
}
